# Generated by Django 4.2.11 on 2024-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_category_remove_user_watchlist_watchlist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(max_length=64),
        ),
    ]
