# Generated by Django 4.2.11 on 2024-04-13 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_auction_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
